### ISSUE TITLE
具体是用什么的算法啊

### ISSUE THREAD

**Issue by hanDasiy** [wyqmath/CUMCM2024#1]

**Comment by wyqmath** [comment]
数学建模国赛C题的代码，请问你是有什么问题吗？

**Comment by hanDasiy** [comment]
无恶意，我只是想问问用的什么算法，想借鉴一下算法，不行的话就算了。



---Original---
From: "Yiquan ***@***.***&gt;
Sent at: 2024年12月18日(Wed) Evening11:27
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wyqmath/CUMCM2024] 具体是用什么的算法啊 (Issue #1)




 
数学建模国赛C题的代码，请问你是有什么问题吗？

**Comment by wyqmath** [comment]
本文介绍了一种利用粒子群优化（PSO）算法的多阶段作物种植策略优化模型。该模型旨在应对农业面临的主要挑战，如市场需求波动、气候多变和生产成本上升。在七年的规划期限内（2024-2030 年），该模型通过整合作物产量、市场价格和作物轮作等因素，动态调整作物种植策略。所提出的框架对作物选择和面积分配进行了优化，在保持可持续实践的同时，最大限度地提高经济收益。与传统的静态模型不同，这种方法考虑到了不确定性，并能适应市场条件的实时变化。该模型能够根据 PSO 调整种植策略，确保农民能够通过灵活的决策优化产量并减少浪费。实验结果表明，该模型能有效地动态优化种植策略，同时满足土地可用性和作物轮作等约束条件。

**Comment by hanDasiy** [comment]
非常感谢！打扰你了，若有冒犯之处，敬请谅解。



---Original---
From: "Yiquan ***@***.***&gt;
Sent at: 2024年12月18日(Wed) Evening11:55
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wyqmath/CUMCM2024] 具体是用什么的算法啊 (Issue #1)




 
本文介绍了一种利用粒子群优化（PSO）算法的多阶段作物种植策略优化模型。该模型旨在应对农业面临的主要挑战，如市场需求波动、气候多变和生产成本上升。在七年的规划期限内（2024-2030 年），该模型通过整合作物产量、市场价格和作物轮作等因素，动态调整作物种植策略。所提出的框架对作物选择和面积分配进行了优化，在保持可持续实践的同时，最大限度地提高经济收益。与传统的静态模型不同，这种方法考虑到了不确定性，并能适应市场条件的实时变化。该模型能够根据 PSO 调整种植策略，确保农民能够通过灵活的决策优化产量并减少浪费。实验结果表明，该模型能有效地动态优化种植策略，同时满足土地可用性和作物轮作等约束条件。

**Comment by wyqmath** [comment]
没关系，感兴趣可以详聊，wyqmath@gmail.com
